# Generated by Django 4.1.7 on 2023-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_average_rating_book_ratings_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
