# Generated by Django 4.1.7 on 2023-06-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='comments',
            new_name='no_of_comments',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ratings',
            new_name='no_of_ratings',
        ),
    ]
